/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package package1;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author KEVIN M.H.D.R.
 */
    
    
public class Menu extends javax.swing.JFrame {
    
    public static Connection connDB()
    {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn=DriverManager.getConnection("jdbc:mysql://localhost/alldata","root","");
            //alldata > database name
            // root > username mysql
            // " " > password mysql
            
            return conn;
        } catch (ClassNotFoundException | SQLException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return null;
    }
    
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        submit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        list = new javax.swing.JTextArea();
        ingin = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        alp = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        kaluku1 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        kaluku2 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        kalukula = new javax.swing.JCheckBox();
        bigi1 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bigi2 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        sidi = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        ako = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        bada1 = new javax.swing.JCheckBox();
        bada2 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        krs = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("180535632545");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, 90, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Kartu Rencana Studi");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("S1 Teknik Informatika");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 470, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Kevin Muhammad Hilmy Dzakwan Raihan");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        getContentPane().add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 80, 30));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 520, -1, -1));

        list.setColumns(20);
        list.setRows(5);
        list.setText(databasis1 + alpro + kalk1 + kalk2 + sisd + ingg);
        jScrollPane3.setViewportView(list);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 90, 310, 140));

        ingin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Algoritma dan Pemrograman", "Kalkulus Lanjut", "Bahasa Inggris Teknik", "Sistem Operasi", "Data Mining" }));
        ingin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inginActionPerformed(evt);
            }
        });
        getContentPane().add(ingin, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Matkul yang ingin diambil");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Algoritma dan Pemrograman");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 80, 230, 20));

        alp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alpActionPerformed(evt);
            }
        });
        getContentPane().add(alp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sudah Diambil");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 60, -1, -1));

        kaluku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaluku1ActionPerformed(evt);
            }
        });
        getContentPane().add(kaluku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Kalkulus 1");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 230, 20));

        kaluku2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kaluku2ActionPerformed(evt);
            }
        });
        getContentPane().add(kaluku2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 140, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Kalkulus 2");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, 230, 20));

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Kalkulus Lanjut");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 170, 230, 20));

        kalukula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kalukulaActionPerformed(evt);
            }
        });
        getContentPane().add(kalukula, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        bigi1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigi1ActionPerformed(evt);
            }
        });
        getContentPane().add(bigi1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 200, -1, -1));

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Bahasa Inggris 1");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 230, 20));

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Bahasa Inggris 2");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, 230, 20));

        bigi2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bigi2ActionPerformed(evt);
            }
        });
        getContentPane().add(bigi2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Sistem Digital");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 230, 20));

        sidi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sidiActionPerformed(evt);
            }
        });
        getContentPane().add(sidi, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 260, -1, -1));

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Arsitektur Komputer");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 230, 20));

        ako.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                akoActionPerformed(evt);
            }
        });
        getContentPane().add(ako, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 290, -1, -1));

        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Basis Data 1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 230, 20));

        bada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bada1ActionPerformed(evt);
            }
        });
        getContentPane().add(bada1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 320, -1, -1));

        bada2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bada2ActionPerformed(evt);
            }
        });
        getContentPane().add(bada2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 350, -1, -1));

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Basis Data 2");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 350, 230, 20));

        krs.setColumns(20);
        krs.setRows(5);
        krs.setText(saya);
        jScrollPane1.setViewportView(krs);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(686, 290, 320, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\KEVIN MUHAMMAD\\Desktop\\-\\background.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        close();
    }//GEN-LAST:event_logoutActionPerformed

    
    
    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        String jadi;
        jadi = (ingin.getSelectedItem().toString());
        
        int state=0;

if ("Algoritma dan Pemrograman".equals(jadi)){
	System.out.println("Matakuliah "+jadi+" telah berhasil diambil");
}
else if("Kalkulus Lanjut".equals(jadi)&&alp.isSelected()){
	state=1;
}
else if("Bahasa Inggris Teknik".equals(jadi)&&alp.isSelected()){
	state=4;
}
else if("Sistem Operasi".equals(jadi)&&alp.isSelected()){
	state=6;
}
else if("Data Mining".equals(jadi)&&alp.isSelected()){
	state=8;
}
else{state=0; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Algoritma dan Pemrograman terlebih dahulu");}

if(state==1){
    if(kaluku1.isSelected()){
	state=2;
    }
    else{state=1; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Kalkulus 1 terlebih dahulu");}
}


if(state==4){
    if(bigi1.isSelected()){
	state=5;
    }
    else{state=4; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Bahasa Inggris 1 terlebih dahulu");}
}

if(state==6){
    if(sidi.isSelected()){
	state=7;
    }
    else{state=6; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Sistem Digital terlebih dahulu");}
}


if(state==8){
    if(bada1.isSelected()){
	state=9;
    }
    else{state=8; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Basis Data 1 terlebih dahulu");}
}

if(state==2){
    if(kaluku2.isSelected()){
	state=3;
    }
    else{state=2; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Kalkulus 2 terlebih dahulu");}
}

if(state==5){
    if(bigi2.isSelected()){
	state=10;
    }
    else{state=5; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Bahasa Inggris 2 terlebih dahulu");}
}

if(state==7){
    if(ako.isSelected()){
	state=11;
    }
    else{state=7; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Arsitektur Komputer terlebih dahulu");}
}

if(state==9){
    if(bada2.isSelected()){
	state=12;
    }
    else{state=9; JOptionPane.showMessageDialog(null,"Anda harus mengambil matakuliah Basis Data 2 terlebih dahulu");}
}

if(state==3 || state==10 || state== 11 || state==12 ){
	System.out.println("Matakuliah "+jadi+" telah berhasil diambil");
}
        
        
    }//GEN-LAST:event_submitActionPerformed

    private void inginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inginActionPerformed

    private void alpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alpActionPerformed

    private void kaluku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaluku1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kaluku1ActionPerformed

    private void kaluku2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kaluku2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kaluku2ActionPerformed

    private void kalukulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kalukulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kalukulaActionPerformed

    private void bigi1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigi1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigi1ActionPerformed

    private void bigi2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bigi2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bigi2ActionPerformed

    private void sidiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sidiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sidiActionPerformed

    private void akoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_akoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_akoActionPerformed

    private void bada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bada1ActionPerformed

    private void bada2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bada2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bada2ActionPerformed
       
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Menu().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ako;
    private javax.swing.JCheckBox alp;
    private javax.swing.JCheckBox bada1;
    private javax.swing.JCheckBox bada2;
    private javax.swing.JCheckBox bigi1;
    private javax.swing.JCheckBox bigi2;
    private javax.swing.JComboBox<String> ingin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JCheckBox kaluku1;
    private javax.swing.JCheckBox kaluku2;
    private javax.swing.JCheckBox kalukula;
    private javax.swing.JTextArea krs;
    private javax.swing.JTextArea list;
    private javax.swing.JButton logout;
    private javax.swing.JCheckBox sidi;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

    private void close() {
        super.dispose();
    }
    
    String saya=" "; 
    basisdata bd = new basisdata();
    algoritmapemrograman ap = new algoritmapemrograman();
    kalkulus1 k1 = new kalkulus1();
    kalkulus2 k2 = new kalkulus2();
    sisdig sd = new sisdig();
    bing bi = new bing();
    String databasis1 = bd.bd1();
    String alpro = ap.dataap();
    String kalk1 = k1.datak1();
    String kalk2 = k2.datak2();
    String sisd = sd.datasd();
    String ingg = bi.databing();
    
    
    private static class basisdata {
        private String bd1() {
                String bd1;
            bd1 = "Nama matkul	: Basis Data \n Hari		: Senin \n Jam			: 1-4 \n Ruang		: H5 202 \n SKS			: 3 \n ---------------- \n"; 
            return bd1;
        }
    }

    private static class algoritmapemrograman {
        private String dataap() {
            String dataap;
            dataap = "Nama matkul	: Algoritma dan Pemrograman \n Hari	: Selasa \n Jam		: 1-3 \n Ruang	: G4 202 \n SKS		: 3 \n ---------------- \n";
            return dataap;
        }
    }
   
    private static class kalkulus1 {
        private String datak1() {
            String datak1;
            datak1 = "Nama matkul	: Kalkulus 1 \n Hari		: Kamis \n Jam		: 5-6 \n Ruang	: H5 402 \n SKS		: 3 \n ---------------- \n";
            return datak1;
        }
    }
    
    private static class kalkulus2 {
        private String datak2() {
            String datak2;
            datak2 = "Nama matkul	: Kalkulus 2 \n Hari		: Senin \n Jam		: 5-6 \n Ruang	: H5 402 \n SKS		: 3 \n ---------------- \n";
            return datak2;
        }
    }

    private static class sisdig {
        private String datasd() {
             String datasd;
             datasd = "Nama matkul	: Sistem Digital \n Hari		: Senin \n Jam		: 7-8 \n Ruang	: H5 302 \n SKS		: 3 \n ---------------- \n";
             return datasd;
        }
    }

    private static class bing {
        private String databing() {
              String databing;
              databing ="Nama matkul	: Bahasa Inggris \n Hari		: Selasa \n Jam		: 7-8 \n Ruang	: H5 302 \n SKS		: 3 \n ---------------- \n";
              return databing;
        }
    }
    }

